[tox]
envlist = lint, typecheck, test


[testenv:lint]
package = skip
allowlist_externals = poetry
commands =
    poetry run black  src tests
    poetry run ruff check --fix src tests

[testenv:lint-check]
package = skip
allowlist_externals = poetry
commands =
    poetry run black --check src tests
    poetry run ruff check src tests

[testenv:typecheck]
package = skip
allowlist_externals = poetry
commands = poetry run pyright src

[testenv:test]
package = skip
allowlist_externals = poetry
commands = poetry run pytest --cov=./src tests/ 
