[tox]
envlist = lint, typecheck, test

[testenv:lint]
package = skip
allowlist_externals = poetry
commands =
    poetry run black --check src tests
    poetry run ruff check src tests
    poetry run ruff format --check src tests

[testenv:typecheck]
package = skip
allowlist_externals = poetry
commands = poetry run pyright src

[testenv:test]
package = skip
allowlist_externals = poetry
commands = poetry run pytest tests/ -v
